
#define NUM_U_REGISTERS 2u
#define NUM_B_REGISTERS 1u
#define NUM_T_REGISTERS 10u


// ---  CPU Slots ---
// t register
#define RM_TRIANGLE_POS_SLOT 0
#define RM_TRIANGLE_INFO_SLOT 1
#define RM_BVH_TREE_SLOT 2
#define RM_TEXTURES_SLOT 3
#define RM_ENVIRONMENT_MAP_SLOT 4

#define RT_SPHERE_DATA_SLOT 5
#define RT_MESH_ENTITY_DATA_SLOT 6
#define RT_DIRECTIONAL_LIGHT_DATA_SLOT 7
#define RT_POINT_LIGHT_DATA_SLOT 8
#define RT_SPOT_LIGHT_DATA_SLOT 9

// b register
#define RT_RENDER_DATA_SLOT 0
#define RZ_RENDER_DATA_SLOT 1

// u register
#define RT_RESULT_BUFFER_SLOT 0
#define RT_ACCUMULATION_BUFFER_SLOT 1


// --- GPU Registers ---
// t register
#define RM_TRIANGLE_POS_GPU_REG t0 // Writing t[RM_TRIANGLE_DATA_SLOT] compiles and runs, but shows "errors" in RaytracerCS.hlsl
#define RM_TRIANGLE_INFO_GPU_REG t1
#define RM_BVH_TREE_GPU_REG t2
#define RM_TEXTURES_GPU_REG t3
#define RM_ENVIRONMENT_MAP_GPU_REG t4

#define RT_SPHERE_DATA_GPU_REG t5
#define RT_MESH_ENTITY_DATA_GPU_REG t6
#define RT_DIRECTIONAL_LIGHT_DATA_GPU_REG t7
#define RT_POINT_LIGHT_DATA_GPU_REG t8
#define RT_SPOT_LIGHT_DATA_GPU_REG t9

// b register
#define RT_RENDER_DATA_GPU_REG b0
#define RZ_RENDER_DATA_GPU_REG b1

// u register
#define RT_RESULT_BUFFER_GPU_REG u0
#define RT_ACCUMULATION_BUFFER_GPU_REG u1