
#define RESULT_BUFFER_GPU_REG u0
#define RESULT_BUFFER_CPU_SLOT 0

#define ACCUMULATION_BUFFER_GPU_REG u1
#define ACCUMULATION_BUFFER_CPU_SLOT 1

#define RENDER_DATA_GPU_REG b0
#define RENDER_DATA_CPU_SLOT 0

#define SPHERE_DATA_GPU_REG t0
#define SPHERE_DATA_CPU_SLOT 0

#define MESH_DATA_GPU_REG t1
#define MESH_DATA_CPU_SLOT 1

#define TRIANGLE_DATA_GPU_REG t2
#define TRIANGLE_DATA_CPU_SLOT 2

#define TEXTURE_ATLAS_DESC_GPU_REG t3
#define TEXTURE_ATLAS_DESC_CPU_SLOT 3

#define TEXTURE_ATLAS_GPU_REG t4
#define TEXTURE_ATLAS_CPU_SLOT 4

#define BVH_TREE_GPU_REG t5
#define BVH_TREE_CPU_SLOT 5
