
#define GPU_REG_RESULT_BUFFER u0
#define CPU_SLOT_RESULT_BUFFER 0u

#define GPU_REG_ACCUMULATION_BUFFER u1
#define CPU_SLOT_ACCUMULATION_BUFFER 1u

#define GPU_REG_SPHERE_DATA t0
#define CPU_SLOT_SPHERE_DATA 0u

#define GPU_REG_TRIANGLE_DATA t1
#define CPU_SLOT_TRIANGLE_DATA 1u

#define GPU_REG_RENDER_DATA b0
#define CPU_SLOT_RENDER_DATA 0u